### ISSUE TITLE
The Issue With "Any" Typings

### ISSUE THREAD

**Issue by Luna-devv** [KingCh1ll/SparkV#211]
## What is any?
The special type `any` is used to tell TypeScript that a variable can be of **any** type. A variable with the type any can be a string, a number and or anything else! When our previous code block is updated to use any, the assignment of a string is allowed, as shown below. You can assign any type to a variable annotated with `any`.

## Why would you not use it?
Using `any` eliminates the type checking provided by TypeScript, which is an important reason for using TypeScript in the first place instead of JavaScript. By using `any`, you expose yourself to problems that are difficult to track and debug, especially when the code is used in production.

In other words, using `any` for a variable type in TypeScript is similar to writing JavaScript.

### 1. Using the correct type
The first (and best) is to use the right type for your variable. All too often, you use any because they are using a function from third-party libraries or external websites (e.g. Stackoverflow) and don't know what type is being returned!

To save time and not understanding what type is being used, you take a shortcut and use `any` for the variable type, which causes problems later when the code is updated (what if the type of the object returned from the third-party library changes? what if you try to access an attribute that is deprecated in new versions of the library?).

Instead, it is important to understand the type that is being returned and type your variable accordingly. Take the time to understand the code you are copying/pasting from somewhere else, and take the time to understand the library you are including in your code. Knowing the type you are using saves time and avoids mistakes, but ensures you understand the code and can solve the problem you are working on.

### 2. Using `unknown`

The second option is to use `unknown` if you do not know the type and want to ensure type safety. When using unknown, you can assign all types to a variable, but you cannot assign a variable with the unknown type to another variable with a type.

According to the [Pull Request](https://github.com/Microsoft/TypeScript/pull/24439), which introduced unknown into TypeScript!

This PR adds a new top type `unknown`, which is the type-safe counterpart to `any`. Anything can be assigned to unknown, but `unknown` can only be assigned to itself and any, with no type assertion or control-flow-based constraint. Similarly, no operations are allowed on an unknown without first an assertion or a restriction to a more specific type.

**Comment by KingCh1ll** [comment]
ok

**Comment by KingCh1ll** [comment]
I was just lazy lol. In the future I will go back and fix all the typings.

**Comment by Luna-devv** [comment]
It is just defeating the point of using TypeScript in the first place, since you use TypeScript for the typings obviously, and I also just checked that you have `// "strict": true`, aka you're not using strict mode which is the 2nd out of 2 reasons to use TypeScript.

Honestly at this point I don't know why you decided to use TypeScript, if you are literally ***avoiding*** ALL POINTS that make TypeScript to what it is.

**Comment by KingCh1ll** [comment]
why do you and digital have to be all over me oml. I know my code quality isn't the best stop fucking harassing me.

**Comment by Digital39999** [comment]
i told you that many times too

**Comment by Digital39999** [comment]
> I use TypeScript mainly because I was bored and wanted to try a new language out, especially since I've been hearing good things about it. I heard from a friend that the language made JavaScript faster, and that was just what I wanted for my Discord bot.

Yes and that friend was me,  I also told you to not go into it if you won't do it properly..

**Comment by KingCh1ll** [comment]
This issue is stale for 25+ days, so it will be closed in 5 more days
